#This config is meant to illustrate more advanced uses of HiddenOre features, including the
# full depth of the tool config and what it means, and how it works in combination with other
# drops and configs.
#
#This is not a valid configuration file and will cause errors if used directly.
# It is broken into sections, small chunks of valid configurations that individually
# would be usable as a config.
#
#If you have any questions don't hesitate to open an issue on the official github:
#  http://www.github.com/DevotedMC/HiddenOre

# SAMPLE ONE: Advanced Tool Specifications
prefix: You found a hidden ore!
alert_user: true
list_drops: true
debug: false
ignore_silktouch: true
tools:
 fancy_dpick:
  template:
   # This specifies a named diamond pickaxe -- a colored name even -- with lore, and two enchantments
   ==: org.bukkit.inventory.ItemStack
   type: DIAMOND_PICKAXE
   meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §dResin
    lore:
    - Marked Item
    enchants:
     DURABILITY: 3
     DIG_SPEED: 4
  ignore:
   # These ignore settings say that a match is achieved if and only if the name, lore, and enchantments
   # and levels of those enchantments are the same as the template. However, we ignore
   # _other_ enchantments meaning if the tool also has silk touch, that's ignored and a match
   # would still be found. Damage/Durability is ignored
   amount: true
   durability: true
   enchants: false
   otherEnchants: true
   enchantsLvl: false
   lore: false
   name: false
  modifiers:
   # These settings mean that whatever drop is associated with this tool, on a match, will have twice
   # the chance of dropping vs. base configuration.
   dropChance: 2.0
   # As well, the size of the drop will be increased by at least 2 and the maximum size of the drop
   # will be expanded by 4.
   minAmount: 2.0
   maxAmount: 4.0
blocks:
 stone:
  material: STONE
  allTypes: true
  dropMultiple: false
  drops:
   washed_out_shulker:
    package:
     # The drop config can get very complex; here is a Named Monster Egg for Shulkers. 
     - ==: org.bukkit.inventory.ItemStack
       type: MONSTER_EGG
       amount: 1
       meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: Pet Shulker
        internal: H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWAPzijNyU4tYmAAAGLDXgUfAAAA
     # Even cooler, you can specify the "block" type of stationary water, and 
     # if transformIsAble is true, the very rock around you will instantly transform
     # into water.
     - ==: org.bukkit.inventory.ItemStack
       type: STATIONARY_WATER
       amount: 1
    tools:
     - fancy_dpick
    minY: 1
    maxY: 131
    chance: 0.001
    minAmount: 4
    maxAmount: 6
    transformIfAble: true